name: Deploy

on:
  workflow_run:
    workflows: ["Publish"]
    branches: [master]
    types: 
    - completed

  workflow_dispatch:

jobs:
  deploy_to_production:
    name: Connect and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Connect And Pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: root
          key: ${{ secrets.PROD_KEY }}
          script: |
            cd /opt/app
            docker-compose down --remove-orphans
            docker-compose pull   
            docker-compose up -d